export const dataWithClasses = [
  {
    id: 'AA',
    fachrichtung: 'Automobil-Assistent/in',
    classes: [
      { id: 'AA21a', class: 'AA21a' },
      { id: 'AA21b', class: 'AA21b' },
      { id: 'AA22a', class: 'AA22a' },
      { id: 'AA22b', class: 'AA22b' },
    ],
  },
  {
    id: 'AF',
    fachrichtung: 'Automobil-Fachmann/-frau',
    classes: [
      { id: 'AF20a', class: 'AF20a' },
      { id: 'AF20b', class: 'AF20b' },
      { id: 'AF20c', class: 'AF20c' },
      { id: 'AF21a', class: 'AF21a' },
      { id: 'AF21b', class: 'AF21b' },
      { id: 'AF21c', class: 'AF21c' },
      { id: 'AF22a', class: 'AF22a' },
      { id: 'AF22b', class: 'AF22b' },
      { id: 'AF22c', class: 'AF22c' },
    ],
  },
  {
    id: 'AM',
    fachrichtung: 'Automobil-Mechatroniker/in',
    classes: [
      { id: 'AM19a', class: 'AM19a' },
      { id: 'AM19b', class: 'AM19b' },
      { id: 'AM20a', class: 'AM20a' },
      { id: 'AM20b', class: 'AM20b' },
      { id: 'AM21a', class: 'AM21a' },
      { id: 'AM21b', class: 'AM21b' },
      { id: 'AM22a', class: 'AM22a' },
      { id: 'AM22b', class: 'AM22b' },
    ],
  },
  {
    id: 'AN',
    fachrichtung: 'Anlagen-/Apparatebauer/in',
    classes: [
      { id: 'AN19a', class: 'AN19a' },
      { id: 'AN20a', class: 'AN20a' },
      { id: 'AN20z', class: 'AN20z' },
      { id: 'AN21a', class: 'AN21a' },
      { id: 'AN21z', class: 'AN21z' },
      { id: 'AN22a', class: 'AN22a' },
    ],
  },
  {
    id: 'AR',
    fachrichtung: 'Automatikmonteur/in',
    classes: [
      { id: 'AR20a', class: 'AR20a' },
      { id: 'AR21a', class: 'AR21a' },
      { id: 'AR22a', class: 'AR22a' },
    ],
  },
  {
    id: 'AU',
    fachrichtung: 'Automatiker/in',
    classes: [
      { id: 'AU19a', class: 'AU19a' },
      { id: 'AU19b', class: 'AU19b' },
      { id: 'AU19c', class: 'AU19c' },
      { id: 'AU19d', class: 'AU19d' },
      { id: 'AU19y', class: 'AU19y' },
      { id: 'AU19z', class: 'AU19z' },
      { id: 'AU20a', class: 'AU20a' },
      { id: 'AU20b', class: 'AU20b' },
      { id: 'AU20c', class: 'AU20c' },
      { id: 'AU20d', class: 'AU20d' },
      { id: 'AU20y', class: 'AU20y' },
      { id: 'AU20z', class: 'AU20z' },
      { id: 'AU21a', class: 'AU21a' },
      { id: 'AU21b', class: 'AU21b' },
      { id: 'AU21c', class: 'AU21c' },
      { id: 'AU21z', class: 'AU21z' },
      { id: 'AU22a', class: 'AU22a' },
      { id: 'AU22b', class: 'AU22b' },
      { id: 'AU22c', class: 'AU22c' },
      { id: 'AU22d', class: 'AU22d' },
      { id: 'AU22z', class: 'AU22z' },
    ],
  },
  {
    id: 'BM',
    fachrichtung: 'Berufsmittelschule',
    classes: [
      { id: 'BM19a', class: 'BM19a' },
      { id: 'BM19c', class: 'BM19c' },
      { id: 'BM19d', class: 'BM19d' },
      { id: 'BM19e', class: 'BM19e' },
      { id: 'BM19f', class: 'BM19f' },
      { id: 'BM20a', class: 'BM20a' },
      { id: 'BM20c', class: 'BM20c' },
      { id: 'BM20d', class: 'BM20d' },
      { id: 'BM20e', class: 'BM20e' },
      { id: 'BM20f', class: 'BM20f' },
      { id: 'BM20v', class: 'BM20v' },
      { id: 'BM20w', class: 'BM20w' },
      { id: 'BM20x', class: 'BM20x' },
      { id: 'BM20y', class: 'BM20y' },
      { id: 'BM20z', class: 'BM20z' },
      { id: 'BM21a', class: 'BM21a' },
      { id: 'BM21b', class: 'BM21b' },
      { id: 'BM21c', class: 'BM21c' },
      { id: 'BM21d', class: 'BM21d' },
      { id: 'BM21e', class: 'BM21e' },
      { id: 'BM21f', class: 'BM21f' },
      { id: 'BM22a', class: 'BM22a' },
      { id: 'BM22b', class: 'BM22b' },
      { id: 'BM22c', class: 'BM22c' },
      { id: 'BM22d', class: 'BM22d' },
      { id: 'BM22e', class: 'BM22e' },
      { id: 'BM22f', class: 'BM22f' },
    ],
  },
  {
    id: 'BM2_',
    fachrichtung: 'Berufsmittelschule 2',
    classes: [
      { id: 'BM2_21a', class: 'BM2_21a' },
      { id: 'BM2_21b', class: 'BM2_21b' },
      { id: 'BM2_22a', class: 'BM2_22a' },
      { id: 'BM2_22b', class: 'BM2_22b' },
    ],
  },
  {
    id: 'BW',
    fachrichtung: 'Berufsmittelschule Wirtschaft',
    classes: [
      { id: 'BW19a', class: 'BW19a' },
      { id: 'BW20a', class: 'BW20a' },
      { id: 'BW21a', class: 'BW21a' },
      { id: 'BW22a', class: 'BW22a' },
      { id: 'BW22b', class: 'BW22b' },
    ],
  },
  {
    id: 'CA',
    fachrichtung: 'Coiffeurgehilfe/in',
    classes: [
      { id: 'CA21a', class: 'CA21a' },
      { id: 'CA22a', class: 'CA22a' },
    ],
  },
  {
    id: 'CF',
    fachrichtung: 'Coiffeur/Coiffeuse',
    classes: [
      { id: 'CF20a', class: 'CF20a' },
      { id: 'CF20b', class: 'CF20b' },
      { id: 'CF21a', class: 'CF21a' },
      { id: 'CF22a', class: 'CF22a' },
    ],
  },
  {
    id: 'EL',
    fachrichtung: 'Elektroniker/in',
    classes: [
      { id: 'EL19a', class: 'EL19a' },
      { id: 'EL19z', class: 'EL19z' },
      { id: 'EL20a', class: 'EL20a' },
      { id: 'EL21a', class: 'EL21a' },
      { id: 'EL22a', class: 'EL22a' },
      { id: 'EL22z', class: 'EL22z' },
    ],
  },
  {
    id: 'IB',
    fachrichtung: 'Informatiker/in Basislehrjahr',
    classes: [
      { id: 'IB19a', class: 'IB19a' },
      { id: 'IB19b', class: 'IB19b' },
      { id: 'IB20a', class: 'IB20a' },
      { id: 'IB20b', class: 'IB20b' },
      { id: 'IB21a', class: 'IB21a' },
      { id: 'IB22a', class: 'IB22a' },
      { id: 'IB22b', class: 'IB22b' },
    ],
  },
  {
    id: 'IC',
    fachrichtung: 'ICT-Fachmann/-frau',
    classes: [
      { id: 'IC20a', class: 'IC20a' },
      { id: 'IC21a', class: 'IC21a' },
      { id: 'IC21b', class: 'IC21b' },
      { id: 'IC22a', class: 'IC22a' },
      { id: 'IC22b', class: 'IC22b' },
    ],
  },
  {
    id: 'IM',
    fachrichtung: 'Informatikmittelschule',
    classes: [
      { id: 'IM20a', class: 'IM20a' },
      { id: 'IM20c', class: 'IM20c' },
      { id: 'IM20d', class: 'IM20d' },
      { id: 'IM20v', class: 'IM20v' },
      { id: 'IM20w', class: 'IM20w' },
      { id: 'IM21a', class: 'IM21a' },
      { id: 'IM21b', class: 'IM21b' },
      { id: 'IM21c', class: 'IM21c' },
      { id: 'IM21d', class: 'IM21d' },
      { id: 'IM21v', class: 'IM21v' },
      { id: 'IM21w', class: 'IM21w' },
      { id: 'IM22a', class: 'IM22a' },
      { id: 'IM22b', class: 'IM22b' },
      { id: 'IM22c', class: 'IM22c' },
      { id: 'IM22d', class: 'IM22d' },
      { id: 'IM22v', class: 'IM22v' },
      { id: 'IM22w', class: 'IM22w' },
    ],
  },
  {
    id: 'IN',
    fachrichtung: 'Informatiker/in',
    classes: [
      { id: 'IN19a', class: 'IN19a' },
      { id: 'IN19b', class: 'IN19b' },
      { id: 'IN19c', class: 'IN19c' },
      { id: 'IM19y', class: 'IM19y' },
      { id: 'IN19z', class: 'IN19z' },
      { id: 'IN20a', class: 'IN20a' },
      { id: 'IN20b', class: 'IN20b' },
      { id: 'IN20c', class: 'IN20c' },
      { id: 'IN20y', class: 'IN20y' },
      { id: 'IN20z', class: 'IN20z' },
      { id: 'IN21a', class: 'IN21a' },
      { id: 'IN21b', class: 'IN21b' },
      { id: 'IN21c', class: 'IN21c' },
      { id: 'IN21y', class: 'IN21y' },
      { id: 'IN21z', class: 'IN21z' },
      { id: 'IN22a', class: 'IN22a' },
      { id: 'IN22b', class: 'IN22b' },
      { id: 'IN22c', class: 'IN22c' },
      { id: 'IN22y', class: 'IN22y' },
      { id: 'IN22z', class: 'IN22z' },
    ],
  },
  {
    id: 'KA',
    fachrichtung: 'Küchenangestellte/r',
    classes: [
      { id: 'KA21a', class: 'KA21a' },
      { id: 'KA22a', class: 'KA22a' },
    ],
  },
  {
    id: 'KC',
    fachrichtung: 'Koch/Köchin',
    classes: [
      { id: 'KC20a', class: 'KC20a' },
      { id: 'KC20b', class: 'KC20b' },
      { id: 'KC20c', class: 'KC20c' },
      { id: 'KC21a', class: 'KC21a' },
      { id: 'KC21b', class: 'KC21b' },
      { id: 'KC22a', class: 'KC22a' },
      { id: 'KC22b', class: 'KC22b' },
      { id: 'KC22c', class: 'KC22c' },
    ],
  },
  {
    id: 'KS',
    fachrichtung: 'Kosmetiker/in',
    classes: [
      { id: 'KS20a', class: 'KS20a' },
      { id: 'KS21a', class: 'KS21a' },
      { id: 'KS22a', class: 'KS22a' },
    ],
  },
  {
    id: 'MB',
    fachrichtung: 'Mediamatiker/in Basislehrjahr',
    classes: [{ id: 'MB22a', class: 'MB22a' }],
  },
  {
    id: 'ME',
    fachrichtung: 'Mediamatiker/in',
    classes: [
      { id: 'ME19a', class: 'ME19a' },
      { id: 'ME19z', class: 'ME19z' },
      { id: 'ME20a', class: 'ME20a' },
      { id: 'ME20b', class: 'ME20b' },
      { id: 'ME21a', class: 'ME21a' },
      { id: 'ME21b', class: 'ME21b' },
      { id: 'ME22a', class: 'ME22a' },
      { id: 'ME22b', class: 'ME22b' },
      { id: 'ME22y', class: 'ME22y' },
    ],
  },
  {
    id: 'PM',
    fachrichtung: 'Polymechaniker/in Konstrukteur/in',
    classes: [
      { id: 'PM19a', class: 'PM19a' },
      { id: 'PM19b', class: 'PM19b' },
      { id: 'PM19c', class: 'PM19c' },
      { id: 'PM19d', class: 'PM19d' },
      { id: 'PM20a', class: 'PM20a' },
      { id: 'PM20b', class: 'PM20b' },
      { id: 'PM20c', class: 'PM20c' },
      { id: 'PM20d', class: 'PM20d' },
      { id: 'PM21a', class: 'PM21a' },
      { id: 'PM21b', class: 'PM21b' },
      { id: 'PM21c', class: 'PM21c' },
      { id: 'PM21z', class: 'PM21z' },
      { id: 'PM22a', class: 'PM22a' },
      { id: 'PM22b', class: 'PM22b' },
      { id: 'PM22c', class: 'PM22c' },
      { id: 'PM22d', class: 'PM22d' },
    ],
  },
  {
    id: 'PR',
    fachrichtung: 'Produktionsmechaniker/in',
    classes: [
      { id: 'PR20a', class: 'PR20a' },
      { id: 'PR20b', class: 'PR20b' },
      { id: 'PR21a', class: 'PR21a' },
      { id: 'PR22a', class: 'PR22a' },
      { id: 'PR22b', class: 'PR22b' },
    ],
  },
  {
    id: 'RA',
    fachrichtung: 'Restaurantangestellte/r',
    classes: [
      { id: 'RA21a', class: 'RA21a' },
      { id: 'RA22a', class: 'RA22a' },
    ],
  },
  {
    id: 'RF',
    fachrichtung: 'Restaurantfachfrau/-mann',
    classes: [
      { id: 'RF20a', class: 'RF20a' },
      { id: 'RF20b', class: 'RF20b' },
      { id: 'RF21a', class: 'RF21a' },
      { id: 'RF22a', class: 'RF22a' },
      { id: 'RF22b', class: 'RF22b' },
    ],
  },
  {
    id: 'TF',
    fachrichtung: 'Strassentransportfachmann/-frau',
    classes: [
      { id: 'TF20a', class: 'TF20a' },
      { id: 'TF20b', class: 'TF20b' },
      { id: 'TF21a', class: 'TF21a' },
      { id: 'TF21b', class: 'TF21b' },
      { id: 'TF22a', class: 'TF22a' },
      { id: 'TF22b', class: 'TF22b' },
    ],
  },
];

export const data = [
  {
    id: 'AA',
    fachrichtung: 'Automobil-Assistent/in',
  },
  {
    id: 'AF',
    fachrichtung: 'Automobil-Fachmann/-frau',
  },
  {
    id: 'AM',
    fachrichtung: 'Automobil-Mechatroniker/in',
  },
  {
    id: 'AN',
    fachrichtung: 'Anlagen-/Apparatebauer/in',
  },
  {
    id: 'AR',
    fachrichtung: 'Automatikmonteur/in',
  },
  {
    id: 'AU',
    fachrichtung: 'Automatiker/in',
  },
  {
    id: 'BM',
    fachrichtung: 'Berufsmittelschule',
  },
  {
    id: 'BM2_',
    fachrichtung: 'Berufsmittelschule 2',
  },
  {
    id: 'BW',
    fachrichtung: 'Berufsmittelschule Wirtschaft',
  },
  {
    id: 'CA',
    fachrichtung: 'Coiffeurgehilfe/in',
  },
  {
    id: 'CF',
    fachrichtung: 'Coiffeur/Coiffeuse',
  },
  {
    id: 'EL',
    fachrichtung: 'Elektroniker/in',
  },
  {
    id: 'IB',
    fachrichtung: 'Informatiker/in Basislehrjahr',
  },
  {
    id: 'IC',
    fachrichtung: 'ICT-Fachmann/-frau',
  },
  {
    id: 'IM',
    fachrichtung: 'Informatikmittelschule',
  },
  {
    id: 'IN',
    fachrichtung: 'Informatiker/in',
  },
  {
    id: 'KA',
    fachrichtung: 'Küchenangestellte/r',
  },
  {
    id: 'KC',
    fachrichtung: 'Koch/Köchin',
  },
  {
    id: 'KS',
    fachrichtung: 'Kosmetiker/in',
  },
  {
    id: 'MB',
    fachrichtung: 'Mediamatiker/in Basislehrjahr',
  },
  {
    id: 'ME',
    fachrichtung: 'Mediamatiker/in',
  },
  {
    id: 'PM',
    fachrichtung: 'Polymechaniker/in Konstrukteur/in',
  },
  {
    id: 'PR',
    fachrichtung: 'Produktionsmechaniker/in',
  },
  {
    id: 'RA',
    fachrichtung: 'Restaurantangestellte/r',
  },
  {
    id: 'RF',
    fachrichtung: 'Restaurantfachfrau/-mann',
  },
  {
    id: 'TF',
    fachrichtung: 'Strassentransportfachmann/-frau',
  },
];
